Public Class frmView
    'Nicolai Skogstad - Peninsula Grammar - Y11 Student
    'Sales and Commission U3AOS1 SAC assignment
    'Version 1.3 (Part 4) of the 4 part exam.

    Dim FirstName(60) As String       'variable for the Name
    Dim saleDate(60) As Date          'variable for date of sale
    Dim ridesBalloon(60) As Single    'variable for number of Balloon rides encountered
    Dim balloonCom(60) As Single      'Variable for the commission generated by number of Balloon rides
    Dim jumpsBungeee(60) As Single    'Variable for number of Bungee jumps encountered
    Dim bungeeCom(60) As Single       'Variable for comission generated by number of bungee jumps
    Dim identify(60) As String
    Dim ViewFormatHeader As String = "{0, 1} {1, 1} {2, 1} {3, 1} {4, 1} {5, 1}" 'for the column Headers in first row, 0, 1, 2, 3 represent the 4 items to be added and the 
    ' 2nd value represents the space avail eg -12 = 12 characters.
    Dim ViewFormatResults As String = "{0, 1} {1, 1} {2, 1} {3, 1} {4, 1} {5, 1}" 'for the actual data presented in each row, 0, 1, 2, 3 represent the 4 items to be added and the 
    ' 2nd value represents the space avail eg -12 = 12 characters
    Dim ViewFormatResults2 As String = "{0, 1}"
    Dim ViewFormatHeader2 As String = "{0, 1}"

    Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
        'Menu button
        frmMenu.Show()
        Me.Hide()
    End Sub

    Private Sub frmView_Load(sender As Object, e As EventArgs) Handles Me.Load

        Dim index As Integer = 1
        ListBox1.Items.Add(String.Format(ViewFormatHeader, "Name" & vbTab & vbTab, "Date of Sale" & vbTab, "Num Rides (B)" & vbTab, "Com Rides (B)" & vbTab, "Num Jumps (BJ)" & vbTab, "Com Jumps (BJ)"))   'Display heading
        'Open file and display results
        FileOpen(1, "dataStore", OpenMode.Input)
        Do While Not EOF(1)     'EOF = end of file
            Input(1, FirstName(index))
            Input(1, saleDate(index))
            Input(1, ridesBalloon(index))
            Input(1, balloonCom(index))
            Input(1, jumpsBungeee(index))
            Input(1, bungeeCom(index))

            ListBox1.Items.Add(String.Format(ViewFormatResults, FirstName(index) & vbTab, saleDate(index).ToShortDateString & vbTab & vbTab, ridesBalloon(index) & vbTab & vbTab, Format(balloonCom(index), "0.0") & vbTab & vbTab, jumpsBungeee(index) & vbTab & vbTab, Format(bungeeCom(index), "0.0")))
            index = index + 1
        Loop                ' Loop until reach EOF (end of file)
        FileClose(1)
        ListBox2.Items.Add(String.Format(ViewFormatHeader2, "Currency Form"))
        FileOpen(1, "dataStoreIdentify", OpenMode.Input)
        Do While Not EOF(1)
            Input(1, identify(index))
            ListBox2.Items.Add(String.Format(ViewFormatResults2, identify(index)))
        Loop
    End Sub

    Private Sub Button2_Click(sender As Object, e As EventArgs) Handles Button2.Click
        End 'Ending the program as the exit button has been clicked
    End Sub
End Class